# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_card', '0037_remove_paymentcardaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheme', '0048_remove_schemeaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCardAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCardAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCardSchemeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCardAccount')),
                ('scheme_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schemeaccountentry',
            unique_together=set([('scheme_account', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcardschemeentry',
            unique_together=set([('payment_card_account', 'scheme_account')]),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcardaccountentry',
            unique_together=set([('payment_card_account', 'user')]),
        ),
    ]
