# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcardschemeentry',
            options={'verbose_name': 'Payment Card to Membership Card Association', 'verbose_name_plural': 'Payment Card to Membership Card Associations'},
        ),
        migrations.AlterField(
            model_name='paymentcardaccountentry',
            name='payment_card_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCardAccount', verbose_name='Associated Payment Card Account'),
        ),
        migrations.AlterField(
            model_name='paymentcardaccountentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.AlterField(
            model_name='paymentcardschemeentry',
            name='payment_card_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCardAccount', verbose_name='Associated Payment Card Account'),
        ),
        migrations.AlterField(
            model_name='paymentcardschemeentry',
            name='scheme_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount', verbose_name='Associated Membership Card Account'),
        ),
        migrations.AlterField(
            model_name='schemeaccountentry',
            name='scheme_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount', verbose_name='Associated Scheme Account'),
        ),
        migrations.AlterField(
            model_name='schemeaccountentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
    ]
