# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_customuser_salt'),
        ('ubiquity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConsent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
