# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-01 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0056_auto_20190228_1356'),
        ('ubiquity', '0002_auto_20181205_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlanDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField()),
                ('display', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('checkbox', models.BooleanField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scheme.Scheme')),
            ],
        ),
    ]
