# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0002_serviceconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardschemeentry',
            name='active_link',
            field=models.BooleanField(default=True),
        ),
    ]
