# Generated by Django 1.11.7 on 2019-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ubiquity", "0003_membershipplandocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplandocument",
            name="url",
            field=models.URLField(verbose_name="document"),
        ),
    ]
