# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0003_paymentcardschemeentry_active_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconsent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
