# Generated by Django 2.2.11 on 2020-05-21 15:05

from django.db import migrations, models


def update_active_status(apps, schema_editor):
    PaymentCardSchemeEntry = apps.get_model('ubiquity', 'PaymentCardSchemeEntry')

    for link in PaymentCardSchemeEntry.objects.all():
        current_status = link.active_link
        print(f"Looking at active_link on PaymentCardSchemeEntry id:{link.id} is {current_status}")
        new_status = link.get_active_status()
        if current_status != new_status:
            link.active_link = new_status
            # link.save()
            print(f"Changed active_link on PaymentCardSchemeEntry id:{link.id} to {new_status} was {current_status}")


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0005_paymentcardschemeentry_vop_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardschemeentry',
            name='active_link',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_active_status),
    ]
