# Generated by Django 2.2.11 on 2020-06-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0049_auto_20200501_0929'),
        ('scheme', '0076_format_stored_balance'),
        ('ubiquity', '0006_auto_20200521_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcardschemeentry',
            name='vop_link',
        ),
        migrations.CreateModel(
            name='VopActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_id', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.IntegerField(choices=[(1, 'activating'), (2, 'deactivating'), (3, 'activated'), (4, 'deactivated')], default=1, help_text='Activation Status')),
                ('payment_card_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_card.PaymentCardAccount', verbose_name='Associated VOP Payment Card Account')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheme.Scheme', verbose_name='Associated Scheme')),
            ],
        ),
    ]
