# Generated by Django 2.2.11 on 2020-06-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0006_auto_20200521_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardschemeentry',
            name='vop_link',
            field=models.IntegerField(choices=[(0, 'undefined'), (1, 'activating'), (2, 'deactivating'), (3, 'activated'), (4, 'deactivated')], default=0, help_text='The status of VOP card activation'),
        ),
    ]
