# Generated by Django 2.2.11 on 2020-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0007_auto_20200630_1032'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vopactivation',
            constraint=models.UniqueConstraint(fields=('payment_card_account', 'scheme'), name='unique_activation'),
        ),
    ]
