# Generated by Django 2.2.14 on 2020-10-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0009_auto_20201007_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccountentry',
            name='auth_status',
            field=models.IntegerField(choices=[(0, 'authorised'), (1, 'unauthorised')], default=1),
        ),
    ]
