# Generated by Django 2.2.24 on 2021-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ubiquity", "0010_schemeaccountentry_auth_provided"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemeaccountentry",
            name="auth_provided",
            field=models.BooleanField(default=False),
        ),
    ]
