# Generated by Django 2.2.24 on 2021-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity', '0011_auto_20210929_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplandocument',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
