# Generated by Django 4.0.3 on 2022-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiquity", "0012_membershipplandocument_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcardschemeentry",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of the PLL link status. This is automatically populated based on the slug.",
            ),
        ),
        migrations.AddField(
            model_name="paymentcardschemeentry",
            name="slug",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("LOYALTY_CARD_PENDING", "LOYALTY_CARD_PENDING"),
                    ("LOYALTY_CARD_NOT_AUTHORISED", "LOYALTY_CARD_NOT_AUTHORISED"),
                    ("PAYMENT_ACCOUNT_PENDING", "PAYMENT_ACCOUNT_PENDING"),
                    ("PAYMENT_ACCOUNT_INACTIVE", "PAYMENT_ACCOUNT_INACTIVE"),
                    ("PAYMENT_ACCOUNT_AND_LOYALTY_CARD_INACTIVE", "PAYMENT_ACCOUNT_AND_LOYALTY_CARD_INACTIVE"),
                    ("PAYMENT_ACCOUNT_AND_LOYALTY_CARD_PENDING", "PAYMENT_ACCOUNT_AND_LOYALTY_CARD_PENDING"),
                    ("UBIQUITY_COLLISION", "UBIQUITY_COLLISION"),
                ],
                default="",
            ),
        ),
        migrations.AddField(
            model_name="paymentcardschemeentry",
            name="state",
            field=models.IntegerField(choices=[(0, "pending"), (1, "active"), (2, "inactive")], default=0),
        ),
    ]
