# Generated by Django 4.0.3 on 2022-05-06 10:19
from ubiquity.models import PaymentCardSchemeEntry as EntryState
from django.db import migrations, transaction


def update_active_link_slugs(apps, schema_editor):
    PaymentCardSchemeEntry = apps.get_model('ubiquity', 'PaymentCardSchemeEntry')
    while PaymentCardSchemeEntry.objects.filter(active_link=True, state=EntryState.PENDING).exists():
        with transaction.atomic():
            batch_ids = PaymentCardSchemeEntry.objects.filter(
                active_link=True, state=EntryState.PENDING
            ).values_list("id")[:10000]
            PaymentCardSchemeEntry.objects.filter(id__in=batch_ids).update(state=EntryState.ACTIVE)


def revert_active_link_slugs(apps, schema_editor):
    PaymentCardSchemeEntry = apps.get_model('ubiquity', 'PaymentCardSchemeEntry')
    while PaymentCardSchemeEntry.objects.filter(active_link=True, state=EntryState.ACTIVE).exists():
        with transaction.atomic():
            batch_ids = PaymentCardSchemeEntry.objects.filter(
                active_link=True, state=EntryState.ACTIVE
            ).values("id")[:10000]
            PaymentCardSchemeEntry.objects.filter(id__in=batch_ids).update(state=EntryState.PENDING)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('ubiquity', '0013_paymentcardschemeentry_description_and_more'),
    ]

    operations = [
        migrations.RunPython(update_active_link_slugs, reverse_code=revert_active_link_slugs),
    ]
