# Generated by Django 4.0.3 on 2022-05-06 10:19
from django.db import migrations, transaction

"""
    In order to prevent test case failure I have changed the setting of state to have the values as set in
    0013_update_active_link_slug.py
    i.e. model_name="paymentcardschemeentry",
            name="state",
            field=models.IntegerField(choices=[(0, "pending"), (1, "active"), (2, "inactive")], default=0),
    Attempts to get the migration to use the status at the time of migration failed once 0017 was applied successfully
    and then the test cases run.
"""


def update_active_link_slugs(apps, schema_editor):
    PaymentCardSchemeEntry = apps.get_model("ubiquity", "PaymentCardSchemeEntry")
    while PaymentCardSchemeEntry.objects.filter(active_link=True, state=0).exists():
        with transaction.atomic():
            batch_ids = PaymentCardSchemeEntry.objects.filter(active_link=True, state=1).values_list("id")[:10000]
            PaymentCardSchemeEntry.objects.filter(id__in=batch_ids).update(state=1)


def revert_active_link_slugs(apps, schema_editor):
    PaymentCardSchemeEntry = apps.get_model("ubiquity", "PaymentCardSchemeEntry")
    while PaymentCardSchemeEntry.objects.filter(active_link=True, state=1).exists():
        with transaction.atomic():
            batch_ids = PaymentCardSchemeEntry.objects.filter(active_link=True, state=1).values("id")[:10000]
            PaymentCardSchemeEntry.objects.filter(id__in=batch_ids).update(state=0)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ubiquity", "0013_paymentcardschemeentry_description_and_more"),
    ]

    operations = [
        migrations.RunPython(update_active_link_slugs, reverse_code=revert_active_link_slugs),
    ]
