# Generated by Django 4.0.7 on 2022-11-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ubiquity", "0017_remove_paymentcardschemeentry_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schemeaccountentry",
            name="auth_provided",
        ),
    ]
