# Generated by Django 4.0.7 on 2022-12-01 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ubiquity", "0018_migrate_pll_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentcardschemeentry",
            name="description",
        ),
        migrations.RemoveField(
            model_name="paymentcardschemeentry",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="paymentcardschemeentry",
            name="state",
        ),
        migrations.RemoveField(
            model_name="schemeaccountentry",
            name="auth_provided",
        ),
    ]
