# Generated by Django 4.2.1 on 2023-05-22 07:33

from django.db import migrations, models
from django.db.models import Q

from ubiquity.models import AccountLinkStatus


def calculate_and_update_authorised(apps, schema_editor):
    SchemeAccountEntry = apps.get_model("ubiquity", "SchemeAccountEntry")

    SchemeAccountEntry.objects.filter(
        ~Q(link_status__in=AccountLinkStatus.exclude_balance_statuses())
        & (Q(link_status=AccountLinkStatus.ACTIVE) | ~Q(scheme_account__balances__in=[{}, []]))
    ).update(authorised=True)


class Migration(migrations.Migration):

    dependencies = [
        ("ubiquity", "0019_remove_paymentcardschemeentry_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemeaccountentry",
            name="authorised",
            field=models.BooleanField(default=False, verbose_name="User has been authorised."),
        ),
        migrations.RunPython(calculate_and_update_authorised, reverse_code=migrations.RunPython.noop),
    ]
