services:
- postgres:9.4.4

variables:
  HERMES_DATABASE_URL:  "postgres://postgres@$POSTGRES_PORT_5432_TCP_ADDR:5432$POSTGRES_NAME"

dev:
  script:
  - env
  - pip3 install -r requirements.txt
  - python3 manage.py test

