tests:
  script:
    - pip3 install --no-index --find-links=/wheelhouse -r requirements.txt
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - py.test --cov=.
  services:
  - postgres:9.4.4

flake8:
  script:
    - flake8 *