stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  script:
    - pip3 install -r requirements.txt
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - coverage run --source='.' manage.py test -v 2
    - coverage report
  services:
    - postgres:9.4.4

complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  script:
    - flake8 *

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/hermes:latest" .
    - docker push "$CI_REGISTRY/hermes:latest"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/hermes:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY/hermes:$CI_COMMIT_TAG"
  only:
    - tags

build-ubiquity:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/hermes:ubiquity" .
    - docker push "$CI_REGISTRY/hermes:ubiquity"
  only:
    - feature/ubiquity

deploy-dev:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: dev
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=dev deploystatic
    - kubectl delete po -n=dev -l=project=hermes
  only:
    - develop

deploy-ubiquity:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: dev
  script:
    - kubectl delete po -n=ukbanking -l=project=hermes
    - kubectl delete po -n=ubiquity -l=project=hermes
  only:
    - feature/ubiquity

deploy-staging:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: staging
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=staging deploystatic
    - 'kubectl patch -n=staging deployment/hermes --patch "{\"spec\": {\"template\": {\"spec\": {\"initContainers\": [{\"name\": \"migrate\",\"image\": \"olympus.azurecr.io/hermes:$CI_COMMIT_TAG\"}]}}}}"'
    - kubectl set image -n=staging deployment/hermes hermes=olympus.azurecr.io/hermes:$CI_COMMIT_TAG
  only:
    - tags

deploy-prod:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: prod
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=prod deploystatic
    - 'kubectl patch -n=production deployment/hermes --patch "{\"spec\": {\"template\": {\"spec\": {\"initContainers\": [{\"name\": \"migrate\",\"image\": \"olympus.azurecr.io/hermes:$CI_COMMIT_TAG\"}]}}}}"'
    - kubectl set image -n=production deployment/hermes hermes=olympus.azurecr.io/hermes:$CI_COMMIT_TAG
  when: manual
  only:
    - tags
