services:
- postgres:9.4.4

before_script:
  - pip3 install -r requirements.txt

tests:
  script:
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - py.test --cov=.

flake8:
  script:
    - flake8 *