tests:
  script:
    - pip3 install -r requirements.txt
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - py.test --cov=.
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy-dev:
  image: hellobink/ansible
  stage: deploy
  environment: dev
  script:
    - cd /ansible && ansible-playbook playbooks/deploy/django.yml -e project=hermes -e hosts=dev_web
  only:
    - master
  tags:
    - docker


deploy-staging:
  stage: deploy
  when: manual
  script:
    - echo 'ansible-playbook playbooks/deploy/django.yml -e project=hermes -e hosts=staging_web'
  environment: staging
  only:
    - master
  tags:
    - docker

deploy-production:
  stage: deploy
  when: manual
  script:
    - echo 'ansible-playbook playbooks/deploy/django.yml -e project=hermes -e hosts=prod_web -e jump=your_otp_user'
  environment: production
  only:
      - master
  tags:
    - docker
