tests:
  script:
    - pip3 install -r requirements.txt
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - py.test --cov=.
  tags:
    - docker
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/hellobink/olympus/hermes/image:build-$CI_PIPELINE_ID -t registry.gitlab.com/hellobink/olympus/hermes/image:latest .
    - docker login registry.gitlab.com -u binkautomation -p $REPO_PASS
    - docker push registry.gitlab.com/hellobink/olympus/hermes/image:latest
    - docker push registry.gitlab.com/hellobink/olympus/hermes/image:build-$CI_PIPELINE_ID
    - docker rmi registry.gitlab.com/hellobink/olympus/hermes/image:latest
    - docker rmi registry.gitlab.com/hellobink/olympus/hermes/image:build-$CI_PIPELINE_ID
  only:
    - master
  tags:
    - shell

