tests:
  script:
    - pip3 install -r requirements.txt
    - export HERMES_DATABASE_URL="postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - echo $HERMES_DATABASE_URL
    - py.test --cov=.
  services:
  - postgres:9.4.4

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  script:
    - flake8 *

deploy:
  image: loyaltyangels/ansible
  stage: deploy
  environment: dev
  script:
  - cd /ansible && ansible-playbook playbooks/deploy/django.yml -e project=hermes -e hosts=dev_web
  only:
  - master