tests:
  variables:
    HERMES_DATABASE_URL: "postgres://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
  script:
    - pip3 install -r requirements.txt
    - py.test --cov=.
  services:
  - postgres:9.4.4

flake8:
  script:
    - flake8 *