# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_squashed_0049_auto_20160118_1112'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scheme',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schemeaccount',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schemeimage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='third_party_identifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schemeimage',
            name='image',
            field=models.ImageField(upload_to='schemes'),
        ),
    ]
