# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_auto_20160217_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeAccountImageCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme')),
                ('scheme_accounts', models.ManyToManyField(to='scheme.SchemeAccount')),
            ],
        ),
    ]
