# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0009_auto_20160426_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='description',
            field=models.CharField(default='desc', max_length=300),
            preserve_default=False,
        ),
    ]
