# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0010_auto_20160426_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers')]),
        ),
        migrations.AlterField(
            model_name='schemeimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers')]),
        ),
    ]
