# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0011_auto_20160511_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='android_app_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='ios_scheme',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='itunes_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='playstore_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
