# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0014_auto_20160512_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Bink'), (2, 'Show')]),
        ),
    ]
