# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0018_auto_20160525_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
