# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0020_auto_20160610_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccount',
            name='order',
            field=models.IntegerField(),
        ),
    ]
