# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0021_auto_20160623_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_donor', models.IntegerField(default=1)),
                ('exchange_rate_host', models.IntegerField(default=1)),
                ('transfer_min', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('transfer_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transfer_multiple', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tip_in_url', models.URLField()),
                ('info_url', models.URLField()),
                ('flag_auto_tip_in', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('transaction_reference', models.CharField(default='Convert', editable=False, max_length=24)),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('donor_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_in', to='scheme.Scheme')),
                ('host_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_in', to='scheme.Scheme')),
            ],
        ),
    ]
