# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0022_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='link_account_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
