# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0023_scheme_link_account_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='forgotten_password_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
