# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0024_auto_20160817_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='Join terms & conditions',
            field=models.TextField(blank=True),
        ),
    ]
