# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0027_auto_20160831_1505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schemeaccountimage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='scheme',
            name='link_account_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='size_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='strap_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
