# Generated by Django 1.9.2 on 2016-10-17 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0028_auto_20160930_0954"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="schemeaccountimage",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="schemeimage",
            managers=[],
        ),
    ]
