# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0029_auto_20161017_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers'), (7, 'promotions')]),
        ),
        migrations.AlterField(
            model_name='schemeimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers'), (7, 'promotions')]),
        ),
    ]
