# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import scheme.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0030_auto_20170406_1401'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schemeaccount',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', scheme.models.ActiveSchemeIgnoreQuestionManager()),
            ],
        ),
        migrations.AddField(
            model_name='schemeaccount',
            name='link_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
