# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0036_auto_20171030_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccountimage',
            name='reward_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schemeimage',
            name='reward_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
