# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0037_auto_20171123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccountimage',
            name='reward_tier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='type',
            field=models.CharField(choices=[('username', 'user name'), ('email', 'email'), ('card_number', 'card number'), ('barcode', 'barcode'), ('password', 'password'), ('place_of_birth', 'place of birth'), ('postcode', 'postcode'), ('memorable_date', 'memorable date'), ('pin', 'pin'), ('title', 'title'), ('first_name', 'first name'), ('last_name', 'last name'), ('favourite_place', 'favourite place'), ('date_of_birth', 'date_of_birth'), ('phone_number', 'phone number')], max_length=250),
        ),
        migrations.AlterField(
            model_name='schemeimage',
            name='reward_tier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
