# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20180524_0958'),
        ('scheme', '0040_auto_20180129_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Property')),
            ],
        ),
        migrations.RemoveField(
            model_name='schemeaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='schemeaccount',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (403, 'Invalid credentials'), (432, 'Invalid mfa'), (530, 'End site down'), (531, 'IP blocked'), (532, 'Tripped captcha'), (5, 'Please check your scheme account login details.'), (434, 'Account locked on end site'), (429, 'Cannot connect, too many retries'), (503, 'Too many balance requests running'), (520, 'An unknown error has occurred'), (9, 'Midas unavailable'), (10, 'Wallet only card'), (404, 'Agent does not exist on midas'), (533, 'Password expired'), (900, 'Join'), (444, 'No user currently found')], default=0),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='options',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Link'), (2, 'Join'), (6, 'Join (optional)'), (3, 'Link & Join')], default=0),
        ),
        migrations.AddField(
            model_name='schemeaccountentry',
            name='scheme_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount'),
        ),
        migrations.AddField(
            model_name='schemeaccount',
            name='prop_set',
            field=models.ManyToManyField(related_name='scheme_account_set', through='scheme.SchemeAccountEntry', to='user.Property'),
        ),
    ]
