# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0042_consent_userconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='scheme.Scheme'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='text',
            field=models.TextField(),
        ),
    ]
