# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 09:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import scheme.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0042_consent_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='transaction_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=scheme.models._default_transaction_headers, size=None),
        ),
        migrations.AlterField(
            model_name='consent',
            name='journey',
            field=models.IntegerField(choices=[(0, 'join'), (1, 'link'), (2, 'add')]),
        ),
        migrations.AlterField(
            model_name='consent',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='scheme.Scheme'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='text',
            field=models.TextField(),
        ),
    ]
