# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0042_consent_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='transaction_headers',
            field=models.CharField(default='Date,Reference,Points', max_length=40),
        ),
    ]
