# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0043_auto_20180820_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='tier',
            field=models.IntegerField(choices=[(1, 'PLL'), (2, 'Basic'), (3, 'Partner')]),
        ),
    ]
