# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 13:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0043_auto_20180820_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeBalanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'balance details',
            },
        ),
        migrations.CreateModel(
            name='SchemeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Tier')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schemeaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='scheme',
            name='authorisation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='digital_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='enrol_incentive',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_name_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schemeaccount',
            name='balances',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
