# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0043_auto_20180611_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='journey',
            field=models.IntegerField(choices=[(0, 'join'), (1, 'link'), (2, 'add')]),
        ),
    ]
