# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0043_auto_20180608_1226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consent',
            managers=[
            ],
        ),
    ]
