# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 13:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubiquity', '0001_initial'),
        ('scheme', '0044_auto_20180823_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='user_set',
            field=models.ManyToManyField(related_name='scheme_account_set', through='ubiquity.SchemeAccountEntry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemeaccountimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='answer_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'sensitive'), (2, 'choice'), (3, 'boolean')], default=0),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='common_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='field_type',
            field=models.IntegerField(blank=True, choices=[(0, 'add'), (1, 'auth'), (2, 'enrol')], null=True),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='validation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schemeimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='tier',
            field=models.IntegerField(choices=[(1, 'PLL'), (2, 'Basic'), (3, 'Partner')]),
        ),
        migrations.AddField(
            model_name='schemedetail',
            name='scheme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme'),
        ),
        migrations.AddField(
            model_name='schemebalancedetails',
            name='scheme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme'),
        ),
    ]
