# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0044_auto_20180615_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCredentialQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme')),
                ('scheme_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='scheme.SchemeCredentialQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeCredentialQuestionChoiceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_values', to='scheme.SchemeCredentialQuestionChoice')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
