# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0044_auto_20180823_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
