# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0046_auto_20180824_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemecredentialquestion',
            name='common_name',
        ),
    ]
