# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0047_auto_20180629_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemeaccount',
            name='user',
        ),
    ]
