# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0047_remove_schemecredentialquestion_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='plan_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='plan_summary',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='schemebalancedetails',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schemebalancedetails',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='schemebalancedetails',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schemebalancedetails',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='validation',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
