# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0047_auto_20180629_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsent',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='user',
        ),
        migrations.AddField(
            model_name='consent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='consent_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconsent',
            name='scheme_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconsent',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
