# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 11:23
from __future__ import unicode_literals

from django.db import migrations


def populate_scheme_statuses(apps, schema_editor):
    ACTIVE = 0
    INACTIVE = 2
    Scheme = apps.get_model('scheme', 'Scheme')
    for scheme in Scheme.all_objects.all():
        scheme.status = ACTIVE if scheme.is_active else INACTIVE
        scheme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0048_auto_20181106_1149'),
    ]

    operations = [
        migrations.RunPython(populate_scheme_statuses,
                             migrations.RunPython.noop),
    ]
