# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-09 13:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0049_schemeaccount_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='balance',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
