# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0050_schemeaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccount',
            name='balance',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
