# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0051_auto_20180710_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccountimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='schemeimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
