# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 14:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0052_auto_20180807_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='authorisation_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='digital_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='enrol_incentive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_name_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='answer_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'sensitive'), (2, 'choice'), (3, 'boolean')], default=0),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='common_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'add_field'), (1, 'auth_field'), (2, 'enrol_field')], default=0),
        ),
        migrations.AddField(
            model_name='schemecredentialquestion',
            name='validation',
            field=models.TextField(default='.*'),
        ),
    ]
