# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0053_auto_20180808_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='common_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
