# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0055_schemebalancedetail_schemedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemeaccount',
            old_name='balance',
            new_name='balances',
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='enrol_incentive',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='plan_summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='field_type',
            field=models.IntegerField(blank=True, choices=[(0, 'add_field'), (1, 'auth_field'), (2, 'enrol_field')], null=True),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='validation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
