# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0056_auto_20180813_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='authorisation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='plan_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='schemecredentialquestion',
            name='field_type',
            field=models.IntegerField(blank=True, choices=[(0, 'add'), (1, 'auth'), (2, 'enrol')], null=True),
        ),
    ]
