# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0056_auto_20190228_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='barcode_redeem_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheme',
            name='plan_register_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
