# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0057_auto_20180815_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeBalanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme')),
            ],
        ),
        migrations.RemoveField(
            model_name='schemebalancedetail',
            name='scheme_id',
        ),
        migrations.DeleteModel(
            name='SchemeBalanceDetail',
        ),
    ]
