# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0058_auto_20180816_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemebalancedetails',
            options={'verbose_name_plural': 'balance details'},
        ),
    ]
