# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-20 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0059_auto_20190319_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemeStatusAssociation',
            new_name='SchemeBundleAssociation',
        ),
    ]
