# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_customuserconsent'),
        ('scheme', '0059_auto_20190510_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeBundleAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Inactive')], default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ClientApplicationBundle')),
            ],
        ),
        migrations.AlterModelManagers(
            name='scheme',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='status',
        ),
        migrations.AddField(
            model_name='schemebundleassociation',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme'),
        ),
    ]
