# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-19 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0060_auto_20190627_1122'),
        ('scheme', '0060_auto_20190618_1526'),
    ]

    operations = [
    ]
