# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0060_auto_20190320_1005'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schemebundleassociation',
            table=None,
        ),
    ]
