# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0060_auto_20190627_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='enrol_incentive',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
