# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-20 09:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0064_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='scheme_account',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_scheme',
        ),
        migrations.AddField(
            model_name='schemeaccount',
            name='vouchers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='voucherscheme',
            name='earn_type',
            field=models.CharField(choices=[('join', 'Join'), ('accumulator', 'Accumulator')], max_length=50, verbose_name='Earn Type'),
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
