# Generated by Django 2.2.7 on 2019-12-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0065_auto_20191018_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherscheme',
            name='body_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voucherscheme',
            name='terms_and_conditions_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='voucherscheme',
            name='subtext',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
