# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-08 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0065_auto_20190920_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherscheme',
            name='earn_target_value',
        ),
    ]
