# Generated by Django 2.2.11 on 2020-05-20 14:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0074_auto_20200519_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='transactions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
