# Generated by Django 2.2.11 on 2020-07-02 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def populate_pll_links(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')
    PaymentCardSchemeEntry = apps.get_model('ubiquity', 'PaymentCardSchemeEntry')

    accounts = {}
    for link in PaymentCardSchemeEntry.objects.filter(active_link=True).all():
        formatted_link = {'id': link.payment_card_account_id, 'active_link': True}

        if link.scheme_account_id in accounts:
            account = accounts[link.scheme_account_id]
            account.pll_links.append(formatted_link)

        else:
            account = link.scheme_account
            account.pll_links = [formatted_link, ]
            accounts[account.id] = account

    SchemeAccount.objects.bulk_update(accounts.values(), ["pll_links"], batch_size=1000)


def revert_populate_pll_links(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('scheme', '0078_schemeaccount_main_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='pll_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(populate_pll_links, revert_populate_pll_links)
    ]
