# Generated by Django 2.2.11 on 2020-07-02 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db.models import Count


def populate_pll_links(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')

    for account in SchemeAccount.objects.annotate(
            links_number=Count('paymentcardschemeentry')
    ).exclude(links_number=0).prefetch_related('paymentcardschemeentry_set').all():
        account.pll_links = [
            {'id': pcard_id, 'active_link': active}
            for pcard_id, active in account.paymentcardschemeentry_set.filter(
                active_link=True).values_list('payment_card_account_id', 'active_link')
        ]
        account.save(update_fields=['pll_links'])


def revert_populate_pll_links(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('scheme', '0078_schemeaccount_main_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccount',
            name='pll_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(populate_pll_links, revert_populate_pll_links)
    ]
