# Generated by Django 2.2.11 on 2020-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0079_schemeaccount_pll_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccount',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='schemeaccount',
            name='card_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='schemeaccount',
            name='main_answer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
    ]
