# Generated by Django 2.2.11 on 2020-07-31 11:36

from django.db import migrations
from __future__ import unicode_literals
from django.contrib.auth.models import Permission
from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import Group, User


def add_read_only_group(apps, schema_editor):

    read_only = Group.objects.create(name="Read Only")
    permissions = Permission.objects.filter(codename__startswith='view')
    for p in permissions:
        read_only.permissions.add(p)


def add_api_user(apps, schema_editor):

    user = User.objects.create_user(username=settings.API_USER, password=settings.API_USER_PASSWORD)
    group = Group.objects.get(name=settings.API_USER_GROUP)
    user.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ('nd_content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_read_only_group),
        migrations.RunPython(add_read_only_users)
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0081_schemeaccount_formatted_images'),
    ]

    operations = [
    ]
