# Generated by Django 2.2.14 on 2020-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0082_voucherscheme_earn_target_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherscheme',
            name='body_text_cancelled',
            field=models.TextField(blank=True, default='voucher body', verbose_name='Cancelled'),
        ),
        migrations.AddField(
            model_name='voucherscheme',
            name='headline_cancelled',
            field=models.CharField(default='Voucher Cancelled', max_length=250, verbose_name='Cancelled'),
        ),
    ]
