# Generated by Django 2.2.14 on 2020-10-05 13:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def convert_empty_tx_dicts_to_list(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')
    for mcard in SchemeAccount.objects.all():
        if not mcard.transactions and isinstance(mcard.transactions, dict):
            mcard.transactions = []
            mcard.save(update_fields=["transactions"])


def revert_empty_tx_dicts_to_list(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')
    for mcard in SchemeAccount.objects.all():
        if not mcard.transactions and isinstance(mcard.transactions, list):
            mcard.transactions = {}
            mcard.save(update_fields=["transactions"])


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0083_auto_20201001_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccount',
            name='transactions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(convert_empty_tx_dicts_to_list, revert_empty_tx_dicts_to_list),
    ]
