# Generated by Django 2.2.14 on 2020-10-05 13:08

import logging

import django.contrib.postgres.fields.jsonb
from django.core.paginator import Paginator
from django.db import migrations

logger = logging.getLogger(__name__)


def convert_empty_tx_dicts_to_list(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')

    scheme_accounts = SchemeAccount.objects.all()
    # Batches of 1000
    scheme_accounts_pages = Paginator(scheme_accounts, 1000)

    for page_num in scheme_accounts_pages.page_range:
        mcards_to_update = []
        for mcard in scheme_accounts_pages.page(page_num):
            if not mcard.transactions and isinstance(mcard.transactions, dict):
                mcard.transactions = []
                mcards_to_update.append(mcard)

            SchemeAccount.objects.bulk_update(mcards_to_update, ["transactions"])
        logger.debug(
            f"scheme migration 0084_auto_20201005_1408 updated {page_num * 1000} \
                scheme accounts out of {scheme_accounts_pages.count}"
        )


def revert_empty_tx_dicts_to_list(apps, schema_editor):
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')

    scheme_accounts = SchemeAccount.objects.all()
    # Batches of 1000
    scheme_accounts_pages = Paginator(scheme_accounts, 1000)

    for page_num in scheme_accounts_pages.page_range:
        mcards_to_update = []
        for mcard in scheme_accounts_pages.page(page_num):
            if not mcard.transactions and isinstance(mcard.transactions, list):
                mcard.transactions = {}
                mcards_to_update.append(mcard)

            SchemeAccount.objects.bulk_update(mcards_to_update, ["transactions"])

        logger.debug(
            f"scheme migration 0084_auto_20201005_1408 reverted {page_num * 1000} \
                scheme accounts out of {scheme_accounts_pages.count}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0083_auto_20201001_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeaccount',
            name='transactions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(convert_empty_tx_dicts_to_list, revert_empty_tx_dicts_to_list),
    ]
