# Generated by Django 2.2.14 on 2020-10-13 14:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0085_scheme_secondary_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeaccountimage',
            name='dark_mode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeimage',
            name='dark_mode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='secondary_colour',
            field=models.CharField(blank=True, default='', help_text='Hex string e.g "#112233"', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#((?:[0-F]{3}){1,2})$', 2), 'Enter a valid \'colour\' in hexadecimal format e.g "#112233"')]),
        ),
    ]
