# Generated by Django 2.2.14 on 2020-11-09 11:15

from django.db import migrations
from django.db.models import F


def lowercase_email_main_answers(apps, schema_editor):
    SchemeCredentialQuestion = apps.get_model('scheme', 'SchemeCredentialQuestion')
    SchemeAccountCredentialAnswer = apps.get_model('scheme', 'SchemeAccountCredentialAnswer')
    SchemeAccount = apps.get_model('scheme', 'SchemeAccount')

    questions = SchemeCredentialQuestion.objects.filter(type="email", manual_question=True)
    # Update SchemeAccountCredentialAnswer objects
    all_answers = SchemeAccountCredentialAnswer.objects.filter(
        question__in=questions,
        scheme_account__is_deleted=False,
    )
    all_answers.update(answer=str(F('answer')).lower())

    # Update main_answer field on SchemeAccounts
    all_scheme_accounts = SchemeAccount.objects.filter(id__in=all_answers.values_list("scheme_account_id", flat=True))
    all_scheme_accounts.update(main_answer=str(F('main_answer')).lower())


def reverse_lowercase_email_main_answers(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0086_auto_20201005_1408'),
    ]

    operations = [
        migrations.RunPython(lowercase_email_main_answers, reverse_code=reverse_lowercase_email_main_answers)
    ]
