# Generated by Django 2.2.14 on 2020-11-09 11:15

from django.db import migrations


def lowercase_email_main_answers(apps, schema_editor):
    SchemeAccountCredentialAnswer = apps.get_model('scheme', 'SchemeAccountCredentialAnswer')

    all_answers = SchemeAccountCredentialAnswer.objects.filter(
        question__manual_question=True,
        question__type="email",
        scheme_account__is_deleted=False,
    ).only("answer", "scheme_account")

    for answer in all_answers:
        lowered_answer = answer.answer.lower()
        answer.answer = lowered_answer
        answer.scheme_account.main_answer = lowered_answer

    all_answers.bulk_update(update_fields=["answer", "scheme_account"])


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0086_auto_20201005_1408'),
    ]

    operations = [
        migrations.RunSQL(
            sql=r'CREATE INDEX main_answer_upper_idx ON scheme_schemeaccount(UPPER(main_answer));',
            reverse_sql=r'DROP INDEX main_answer_upper_idx;'
        ),
    ]
