# Generated by Django 2.2.14 on 2020-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0086_auto_20201005_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemebundleassociation',
            name='test_scheme',
            field=models.BooleanField(default=False),
        ),
    ]
