# Generated by Django 2.2.14 on 2020-11-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0087_schemebundleassociation_test_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='test_scheme',
        ),
    ]
