# Generated by Django 2.2.14 on 2020-10-22 14:04

from django.db import migrations, models
import scheme.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0088_delete_main_answer_duplicate_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (3, 'NOT_SENT')], default=scheme.models.ConsentStatus(0)),
        ),
    ]
