# Generated by Django 2.2.14 on 2020-12-24 08:54

from django.db import migrations, models


def zero_to_hero(apps, schema_editor):
    # the new cta_url field will be shown only for membership_plans
    SchemeImage = apps.get_model("scheme", "SchemeImage")
    SchemeImage.objects.filter(call_to_action="0").update(call_to_action="")


def hero_to_zero(apps, schema_editor):
    SchemeImage = apps.get_model("scheme", "SchemeImage")
    SchemeImage.objects.filter(call_to_action="").update(call_to_action="0")


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0090_auto_20201118_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemeaccountimage", name="call_to_action", field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="schemeimage", name="call_to_action", field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(zero_to_hero, reverse_code=hero_to_zero),
    ]
