# Generated by Django 2.2.14 on 2020-12-24 08:54

from django.db import migrations, models


def remove_cta_placeholders(apps, schema_editor):
    # the new cta_url field will be shown only for membership_plans
    SchemeImage = apps.get_model("scheme", "SchemeImage")
    SchemeImage.objects.update(call_to_action="")


def add_cta_placeholders(apps, schema_editor):
    SchemeImage = apps.get_model("scheme", "SchemeImage")
    SchemeImage.objects.update(call_to_action="CTA")


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0090_auto_20201118_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemeaccountimage", name="call_to_action", field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="schemeimage", name="call_to_action", field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(remove_cta_placeholders, reverse_code=add_cta_placeholders),
    ]
