# Generated by Django 2.2.14 on 2021-05-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0093_scheme_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='order',
            new_name='plan_popularity',
        ),
    ]
