# Generated by Django 2.2.24 on 2021-06-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0095_auto_20210518_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOverrideError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.TextField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)])),
                ('error_slug', models.TextField()),
                ('message', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme')),
            ],
            options={
                'unique_together': {('reason_code', 'scheme')},
            },
        ),
    ]
