# Generated by Django 2.2.24 on 2021-12-13 11:26

import re

import django.core.validators
from django.db import migrations, models


def default_blank_text_colour(apps, schema_editor):
    Scheme = apps.get_model("scheme", "Scheme")

    Scheme.objects.update(text_colour="")


def revert_default_blank_text_colour(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0099_schemeaccount_originating_journey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="text_colour",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Hex string e.g "#112233"',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#((?:[0-F]{3}){1,2})$", 2),
                        "Enter a valid 'colour' in hexadecimal format e.g \"#112233\"",
                    )
                ],
            ),
        ),
        migrations.RunPython(default_blank_text_colour, reverse_code=revert_default_blank_text_colour),
    ]
