# Generated by Django 4.0.3 on 2022-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0101_auto_20220113_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="formatted_images",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="schemeaccount",
            name="balances",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="schemeaccount",
            name="formatted_images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="schemeaccount",
            name="pll_links",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="schemeaccount",
            name="transactions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="schemeaccount",
            name="vouchers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="metadata",
            field=models.JSONField(),
        ),
    ]
