# Generated by Django 4.0.4 on 2022-06-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_customuser_bundle_id'),
        ('scheme', '0104_alter_schemeaccount_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeoverrideerror',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clientapplicationbundle'),
        ),
    ]
