# Generated by Django 4.0.5 on 2022-06-29 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0055_alter_customuser_bundle_id"),
        ("scheme", "0105_schemeoverrideerror_channel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schemeoverrideerror",
            unique_together={("error_code", "scheme", "channel")},
        ),
    ]
