# Generated by Django 4.0.6 on 2022-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0106_alter_schemeoverrideerror_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherscheme",
            name="barcode_type",
            field=models.IntegerField(
                choices=[
                    (0, "CODE128 (B or C)"),
                    (1, "QrCode"),
                    (2, "AztecCode"),
                    (3, "Pdf417"),
                    (4, "EAN (13)"),
                    (5, "DataMatrix"),
                    (6, "ITF (Interleaved 2 of 5)"),
                    (7, "Code 39"),
                    (9, "Barcode Not Supported"),
                ]
            ),
        ),
    ]
