# Generated by Django 4.0.6 on 2022-09-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0109_rename_main_answer_schemeaccount_alt_main_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schemeaccount",
            name="status",
        ),
    ]
