# Generated by Django 4.0.6 on 2022-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0109_alter_schemeaccountcredentialanswer_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schemeaccountcredentialanswer",
            name="scheme_account",
        ),
    ]
