# Generated by Django 4.0.9 on 2023-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0111_remove_schemeaccount_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherscheme",
            name="body_text_pending",
            field=models.TextField(blank=True, default="", verbose_name="Pending"),
        ),
        migrations.AddField(
            model_name="voucherscheme",
            name="headline_pending",
            field=models.CharField(default="", max_length=250, verbose_name="Pending"),
        ),
    ]
