# Generated by Django 4.0.10 on 2023-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0112_voucherscheme_body_text_pending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="go_live",
            field=models.DateField(null=True, blank=True),
        ),
    ]
