# Generated by Django 4.0.10 on 2023-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0113_scheme_go_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemecredentialquestion",
            name="validation_description",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
    ]
