# Generated by Django 4.2.1 on 2023-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheme", "0114_schemecredentialquestion_validation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemecredentialquestion",
            name="is_optional",
            field=models.BooleanField(
                default=False, help_text="Whether this field is optional for Enrol & Register credentials"
            ),
        ),
    ]
