# Generated by Django 4.2.3 on 2023-09-05 14:51

from django.db import migrations, models


def set_existing_voucher_schemes_as_default(apps, schema_editor):
    VoucherScheme = apps.get_model("scheme", "VoucherScheme")
    VoucherScheme.objects.annotate(scheme_count=models.Count("scheme__voucherscheme")).filter(scheme_count=1).update(
        default=True
    )


def revert(apps, schema_editor):
    VoucherScheme = apps.get_model("scheme", "VoucherScheme")
    VoucherScheme.objects.annotate(scheme_count=models.Count("scheme__voucherscheme")).filter(scheme_count=1).update(
        default=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0118_voucherscheme_default_voucherscheme_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherscheme",
            name="default",
            field=models.BooleanField(
                default=True, help_text="Default voucher scheme when multiple are available for a scheme"
            ),
        ),
        migrations.RunPython(set_existing_voucher_schemes_as_default, reverse_code=revert),
    ]
