# Generated by Django 4.2.4 on 2023-09-27 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0119_alter_voucherscheme_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemebundleassociation",
            name="plan_popularity",
            field=models.IntegerField(
                blank=True,
                help_text="positive number, 1 being the most popular",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
