# Generated by Django 4.2.4 on 2023-10-11 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0120_schemebundleassociation_plan_popularity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherscheme",
            name="expiry_months",
        ),
    ]
