# Generated by Django 4.2.4 on 2023-10-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_card", "0059_vopmerchantgroup_vopmerchantgroup_unique_default"),
        ("scheme", "0121_remove_voucherscheme_expiry_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="vop_merchant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="If not set, will fallback to the default VopMerchantGroup",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schemes",
                to="payment_card.vopmerchantgroup",
            ),
        ),
    ]
