# Generated by Django 4.2.10 on 2024-03-05 17:16

from django.db import migrations, models


def set_default_is_stored(apps, schema_editor):
    SchemeCredentialQuestion = apps.get_model("scheme", "SchemeCredentialQuestion")
    # Join only
    SchemeCredentialQuestion.objects.filter(options=2).update(is_stored=False)


class Migration(migrations.Migration):
    dependencies = [
        ("scheme", "0122_scheme_vop_merchant_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemecredentialquestion",
            name="is_stored",
            field=models.BooleanField(
                default=True,
                help_text="Whether the answer is stored long-term or disposed of after the initial request",
            ),
        ),
        migrations.RunPython(set_default_is_stored),
    ]
