# Generated by Django 2.2.14 on 2020-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptresult',
            name='apply',
            field=models.IntegerField(choices=[(0, 'No correction available'), (1, 'Mark as deactivated as same token is also active'), (2, 'Transfer activation to card with same token'), (3, 'Re-enrol, Deactivate, Uenroll'), (4, 'Re-enroll'), (5, 'Deactivate, Uenroll'), (6, 'Uenroll')], db_index=True, default=0, help_text='Correction to Apply Now'),
        ),
        migrations.AlterField(
            model_name='scriptresult',
            name='correction',
            field=models.IntegerField(choices=[(0, 'No correction available'), (1, 'Mark as deactivated as same token is also active'), (2, 'Transfer activation to card with same token'), (3, 'Re-enrol, Deactivate, Uenroll'), (4, 'Re-enroll'), (5, 'Deactivate, Uenroll'), (6, 'Uenroll')], db_index=True, default=0, help_text='Correction Required'),
        ),
    ]
