# Generated by Django 2.2.14 on 2020-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20201103_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptresult',
            name='script_item',
        ),
        migrations.AddField(
            model_name='scriptresult',
            name='item_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
