# Generated by Django 4.0.10 on 2023-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0008_alter_scriptresult_apply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptresult",
            name="script_run_uid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
