# Generated by Django 4.2.3 on 2023-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0011_alter_scriptresult_apply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptresult",
            name="apply",
            field=models.IntegerField(
                choices=[
                    (0, "No correction available"),
                    (1, "Mark as deactivated as same token is also active"),
                    (2, "VOP Activate"),
                    (3, "Re-enrol, VOP Deactivate, VOP Un-enroll"),
                    (4, "VOP Re-enroll"),
                    (5, "VOP Deactivate"),
                    (6, "VOP Un-enroll"),
                    (7, "VOP Fix-enroll"),
                    (8, "Retain"),
                    (9, "Retain, VOP Fix-Enroll"),
                    (10, "VOP Un-enroll, VOP Re-Enroll, VOP Set Active"),
                    (2007, "AMEX Un-enroll, AMEX Re-Enroll, AMEX Set Active"),
                    (2008, "Mastercard Un-enroll, Mastercard Re-Enroll, Mastercard Set Active"),
                    (11, "Set Active"),
                    (12, "VOP Multiple Deactivate Unenrol"),
                    (13, "Remove, Deactivate and unenrol,"),
                    (1001, "Mark as Unknown"),
                    (1002, "Refresh Balance"),
                    (2001, "Update Payment Card Hash"),
                    (2002, "Remove Payment Card Account"),
                    (2003, "Delete Payment Card Account"),
                    (2004, "Remove, Un_enroll, Delete Payment Card Account"),
                    (2005, "UN-ENROLL Payment Card Account"),
                    (2006, "RE-ENROLL Payment Card Account"),
                    (3001, "Update PLL Active Link"),
                    (4001, "Delete card links for deleted Users"),
                    (5001, "Run delete process for Bink client users"),
                ],
                db_index=True,
                default=0,
                help_text="Correction to Apply Now",
            ),
        ),
        migrations.AlterField(
            model_name="scriptresult",
            name="correction",
            field=models.IntegerField(
                choices=[
                    (0, "No correction available"),
                    (1, "Mark as deactivated as same token is also active"),
                    (2, "VOP Activate"),
                    (3, "Re-enrol, VOP Deactivate, VOP Un-enroll"),
                    (4, "VOP Re-enroll"),
                    (5, "VOP Deactivate"),
                    (6, "VOP Un-enroll"),
                    (7, "VOP Fix-enroll"),
                    (8, "Retain"),
                    (9, "Retain, VOP Fix-Enroll"),
                    (10, "VOP Un-enroll, VOP Re-Enroll, VOP Set Active"),
                    (2007, "AMEX Un-enroll, AMEX Re-Enroll, AMEX Set Active"),
                    (2008, "Mastercard Un-enroll, Mastercard Re-Enroll, Mastercard Set Active"),
                    (11, "Set Active"),
                    (12, "VOP Multiple Deactivate Unenrol"),
                    (13, "Remove, Deactivate and unenrol,"),
                    (1001, "Mark as Unknown"),
                    (1002, "Refresh Balance"),
                    (2001, "Update Payment Card Hash"),
                    (2002, "Remove Payment Card Account"),
                    (2003, "Delete Payment Card Account"),
                    (2004, "Remove, Un_enroll, Delete Payment Card Account"),
                    (2005, "UN-ENROLL Payment Card Account"),
                    (2006, "RE-ENROLL Payment Card Account"),
                    (3001, "Update PLL Active Link"),
                    (4001, "Delete card links for deleted Users"),
                    (5001, "Run delete process for Bink client users"),
                ],
                db_index=True,
                default=0,
                help_text="Correction Required",
            ),
        ),
    ]
