# Generated by Django 2.2.14 on 2021-01-15 12:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentCardAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=6)),
                ('instance_id', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentCardAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=6)),
                ('instance_id', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('payment_card_account_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSchemeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=6)),
                ('instance_id', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSchemeAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=6)),
                ('instance_id', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('scheme_account_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
