# Generated by Django 2.2.25 on 2022-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0006_auto_20210126_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcustomuser",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentcardaccount",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentcardaccountentry",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentcardschemeentry",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalschemeaccount",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalschemeaccountentry",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvopactivation",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
