# Generated by Django 4.0.7 on 2022-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0009_historicalcustomuser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalschemeaccountentry",
            name="link_status",
            field=models.IntegerField(null=True),
        ),
    ]
