# List of my360 slugs and their respective api endpoint IDs
# Linked to Midas my360endpoints.py

SCHEME_API_DICTIONARY = {
    'cOqQmR': 'stansted-farm',
    'KbeClr': 'the-courtyard',
    'Be_11k': '19-fourteas-tea-rooms',
    'UMxcnJ': 'bored-of-southsea',
    'jpKJgU': 'game-over',
    'HBWF65': 'watkins-and-faux',
    'j5yAeE': 'northney-farm',
    'NuNLGE': 'shakeadelic',
    'iup7wK': 'drift-bar',
    'C3HSb3': 'poppins-restaurant',
    '9jRSrq': 'polka-dot-piercing',
    'YSNMxs': 'nanoo-hair',
    'GK4Tvh': 'comics-games-and-coffee',
    'cM_Nh7': 'the-richmond',
    'K7yej1': 'cliff-roe-sports',
    'mchell': 'michael-chell',
    '-fdK4i': 'the-food-cellar',
    'hewtts': 'hewetts',
    'fitstu': 'fit-stuff',
    'rz22p1': 'cafe-copia',
    'bearga': 'bear-garden',
    '5rRCqF': 'fresco-delikafessen',
    'hsport': 'henley-sports',
    'c1k2ks': 'the-chocolate-cafe',
    'pQ1Pq1': 'ted-james-barbershop',
    'iIEWRM': 'bubble-city',
    'knT_d_': 'turners-pies',
    'XgnCp2': 'gatsby-menswear',
    'lindah': 'linda-h',
    'tiffin': 'tiffin-tea-rooms',
    'bDqM2P': 'hilites-hair-and-beauty',
    'P1irNK': 'dhaba-lane',
    'KP6_Ox': 'el-mexicana',
    '6qF7x1': 'deep-blue-restaurants',
    # List of schemes to be added but no API code yet
    # '': 'mad-hatters',
    # '': 'peewees',
    # '': 'the-vestry',
    # '': 'laurence-menswear',
    # '': 'celo-tan-and-lash',
    # '': 'moffats',
    # '': 'strawberry-vibes',
    # '': 'magoos',
    # '': 'ians-barbers',
    # '': 'everybody-pilates',
    # '': 'nevaeh-hair',
    # '': 'the-marmion',
    # '': 'funland',
    # '': 'the-nags-head',
    # '': 'beauty-clinic',
    # '': 'grit-gym-mma-and-fitness',
    # '': 'the-coffee-co',
    # '': 'thousand-hills',
    # '': 'urban-food',
    # '': 'tennessee-chicken',
}
