# List of my360 slugs and their respective api endpoint IDs

SCHEME_API_DICTIONARY = {
    'coqqmr': 'stansted-farm',
    'kbeclr': 'the-courtyard',
    'be_11k': '19-fourteas-tea-rooms',
    'umxcnj': 'bored-of-southsea',
    'jpkjgu': 'game-over',
    'hbwf65': 'watkins-and-faux',
    'j5yaee': 'northney-farm',
    'nunlge': 'shakeadelic',
    'iup7wk': 'drift-bar',
    'c3hsb3': 'poppins-restaurant',
    '9jrsrq': 'polka-dot-piercing',
    'ysnmxs': 'nanoo-hair',
    'gk4tvh': 'comics-games-and-coffee',
    'cm_nh7': 'the-richmond',
    'k7yej1': 'cliff-roe-sports',
    'mchell': 'michael-chell',
    '-fdK4i': 'the-food-cellar',
    'hewtts': 'hewetts',
    'fitstu': 'fit-stuff',
    'rz22p1': 'cafe-copia',
    'bearga': 'bear-garden',
    '5rrcqf': 'fresco-delikafessen',
    'hsport': 'henley-sports',
    'c1k2ks': 'the-chocolate-cafe',
    'pq1pq1': 'ted-james-barbershop',
    'iiewrm': 'bubble-city',
    'knt_d_': 'turners-pies',
    'xgncp2': 'gatsby-menswear',
    'lindah': 'linda-h',
    'tiffin': 'tiffin-tea-rooms',
    'bdqm2p': 'hilites-hair-and-beauty',
    'p1irnk': 'dhaba-lane',
    'kp6_ox': 'el-mexicana',
    '6qf7x1': 'deep-blue-restaurants',
    # List of schemes to be added but no API code yet
    # '': 'mad-hatters',
    # '': 'peewees',
    # '': 'the-vestry',
    # '': 'laurence-menswear',
    # '': 'celo-tan-and-lash',
    # '': 'moffats',
    # '': 'strawberry-vibes',
    # '': 'magoos',
    # '': 'ians-barbers',
    # '': 'everybody-pilates',
    # '': 'nevaeh-hair',
    # '': 'the-marmion',
    # '': 'funland',
    # '': 'the-nags-head',
    # '': 'beauty-clinic',
    # '': 'grit-gym-mma-and-fitness',
    # '': 'the-coffee-co',
    # '': 'thousand-hills',
    # '': 'urban-food',
    # '': 'tennessee-chicken',
}
