# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0013_auto_20160128_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='reset_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
