# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetail_reset_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='reset_link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
