# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_setting_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme'),
        ),
    ]
