# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160523_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'general'), (1, 'marketing'), (2, 'scheme')], null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
