# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160524_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Marketing'), (2, 'Scheme')], null=True),
        ),
    ]
