# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170317_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=user.models._get_random_string, max_length=128, unique=True)),
                ('secret', models.CharField(blank=True, db_index=True, default=user.models._get_random_string, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
