# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapplication',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='client_id',
            field=models.CharField(db_index=True, default=user.models._get_random_string, max_length=128, primary_key=True, serialize=False),
        ),
    ]
