# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 11:56
from __future__ import unicode_literals

from django.db import migrations


def create_bink_models(apps, schema_editor):
    Organisation = apps.get_model('user', 'Organisation')
    org = Organisation.objects.create(name='Loyalty Angels')
    ClientApplication = apps.get_model('user', 'ClientApplication')
    ClientApplication.objects.create(
        client_id='MKd3FfDGBi1CIUQwtahmPap64lneCa2R6GvVWKg6dNg4w9Jnpd',
        organisation=org,
        name='Bink')


def uncreate_bink_models(apps, schema_editor):
    Organisation = apps.get_model('user', 'Organisation')
    Organisation.objects.filter(name='Loyalty Angels').delete()
    ClientApplication = apps.get_model('user', 'ClientApplication')
    ClientApplication.objects.filter(name='Bink').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_add_org_to_clientapp__create_clientappbundle'),
    ]

    operations = [
        migrations.RunPython(create_bink_models, uncreate_bink_models),
    ]
