# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 16:45
from __future__ import unicode_literals

from django.db import migrations


BINK_APP_ID = 'MKd3FfDGBi1CIUQwtahmPap64lneCa2R6GvVWKg6dNg4w9Jnpd'


def create_bink_bundle(apps, schema_editor):
    Bundle = apps.get_model('user', 'ClientApplicationBundle')
    Bundle.objects.create(client_application_id=BINK_APP_ID, bundle_id='com.bink.wallet')


def undo_bink_bundle(apps, schema_editor):
    Bundle = apps.get_model('user', 'ClientApplicationBundle')
    Bundle.objects.filter(bundle_id='com.bink.wallet').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20170327_1640'),
    ]

    operations = [
        migrations.RunPython(create_bink_bundle, undo_bink_bundle),
    ]
