# Generated by Django 1.9.2 on 2017-03-28 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_data_bink_clientapplication_secret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientapplicationbundle",
            old_name="client_application",
            new_name="client",
        ),
    ]
