# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20170328_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplicationKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_name', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ClientApplication')),
            ],
        ),
    ]
