# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_interim_nonunique_secret_clientapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplication',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Organisation'),
        ),
        migrations.AlterField(
            model_name='clientapplicationbundle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.ClientApplication'),
        ),
        migrations.AlterField(
            model_name='clientapplicationkit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.ClientApplication'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(default='MKd3FfDGBi1CIUQwtahmPap64lneCa2R6GvVWKg6dNg4w9Jnpd', on_delete=django.db.models.deletion.PROTECT, to='user.ClientApplication'),
        ),
    ]
