# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20170403_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
