# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=8)),
                ('client', models.ForeignKey(default='MKd3FfDGBi1CIUQwtahmPap64lneCa2R6GvVWKg6dNg4w9Jnpd', on_delete=django.db.models.deletion.PROTECT, to='user.ClientApplication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='client',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salt',
        ),
    ]
