# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_enabled',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='setting',
            name='journey',
            field=models.IntegerField(blank=True, choices=[(0, 'join'), (1, 'link')], null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='required',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Marketing'), (2, 'Loyalty Scheme'), (3, 'Preferences')], null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.IntegerField(choices=[(0, 'number'), (1, 'string'), (2, 'boolean'), (3, 'text message')]),
        ),
    ]
