# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0037_auto_20180823_1419'),
        ('scheme', '0044_auto_20180823_1419'),
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='issuers',
            field=models.ManyToManyField(blank=True, to='payment_card.Issuer'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='scheme.Scheme'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
