# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 09:04
from __future__ import unicode_literals
import base64
import os

from django.db import migrations


def generate_salts(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    for user in CustomUser.objects.all():
        user.salt = base64.b64encode(os.urandom(16))[:8].decode('utf-8')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.RunPython(generate_salts, lambda apps, schema_editor: None),
    ]
