# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0039_paymentcardaccount_consent'),
        ('scheme', '0051_auto_20180710_1514'),
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='issuers',
            field=models.ManyToManyField(blank=True, to='payment_card.Issuer'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='scheme.Scheme'),
        ),
    ]
