# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0038_auto_20181107_1158'),
        ('scheme', '0052_auto_20181107_1158'),
        ('user', '0031_customuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='issuers',
            field=models.ManyToManyField(blank=True, to='payment_card.Issuer'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='scheme.Scheme'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([]),
        ),
    ]
