# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20180731_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
