# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20180529_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='default_value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='journey',
            field=models.IntegerField(blank=True, choices=[(0, 'join'), (1, 'link'), (2, 'link and join')], null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
