# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20180807_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([]),
        ),
    ]
