# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20180828_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
