# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-02 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20190109_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserConsent',
            fields=[
            ],
            options={
                'verbose_name': 'Custom user service consent',
                'verbose_name_plural': 'Custom user service consents',
                'proxy': True,
                'indexes': [],
            },
            bases=('user.customuser',),
        ),
    ]
