# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0060_auto_20190627_1122'),
        ('user', '0035_customuserconsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapplicationbundle',
            old_name='issuers',
            new_name='issuer',
        ),
        migrations.RemoveField(
            model_name='clientapplicationbundle',
            name='schemes',
        ),
        migrations.AddField(
            model_name='clientapplicationbundle',
            name='scheme',
            field=models.ManyToManyField(blank=True, related_name='related_bundle', through='scheme.SchemeBundleAssociation', to='scheme.Scheme'),
        ),
    ]
