# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0061_auto_20190320_1206'),
        ('user', '0035_remove_clientapplicationbundle_schemes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapplicationbundle',
            old_name='issuers',
            new_name='issuer',
        ),
        migrations.AddField(
            model_name='clientapplicationbundle',
            name='scheme',
            field=models.ManyToManyField(blank=True, through='scheme.SchemeBundleAssociation', to='scheme.Scheme'),
        ),
    ]
