# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-16 13:23
from __future__ import unicode_literals

from django.db import migrations


def create_service_client_app(apps, schema_editor):
    Organisation = apps.get_model('user', 'Organisation')
    ClientApplication = apps.get_model('user', 'ClientApplication')
    ClientApplicationBundle = apps.get_model('user', 'ClientApplicationBundle')

    bink_org = Organisation.objects.get_or_create(name="Loyalty Angels")

    daedalus_client = ClientApplication.objects.create(organisation=bink_org, name="Daedalus")
    ClientApplicationBundle.objects.create(client=daedalus_client, bundle_id="com.bink.daedalus")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_customuser_is_tester'),
    ]

    operations = [
        migrations.RunPython(create_service_client_app),
    ]
