# Generated by Django 2.2.11 on 2020-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20191028_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
