# Generated by Django 2.2.11 on 2020-05-18 08:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_customuser_apple'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
