# Generated by Django 2.2.14 on 2021-02-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20200812_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplicationbundle',
            name='magic_lifetime',
            field=models.DecimalField(blank=True, decimal_places=1, default='1.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='clientapplicationbundle',
            name='magic_link_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
