# Generated by Django 2.2.14 on 2021-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20210226_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplicationbundle',
            name='external_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
