# Generated by Django 2.2.19 on 2021-04-20 15:00

from django.db import migrations

import user.forms


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0048_auto_20210419_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientapplicationbundle",
            name="template",
            field=user.forms.MagicLinkTemplateFileField(blank=True, null=True, upload_to="magic_link_templates"),
        ),
    ]
