# Generated by Django 2.2.24 on 2021-09-29 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20210929_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplicationbundle',
            name='access_token_lifetime',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='access token life (mins)'),
        ),
        migrations.AlterField(
            model_name='clientapplicationbundle',
            name='magic_lifetime',
            field=models.PositiveIntegerField(blank=True, default=60, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='magic link life(mins)'),
        ),
        migrations.AlterField(
            model_name='clientapplicationbundle',
            name='refresh_token_lifetime',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='refresh token life (mins)'),
        ),
    ]
