# Generated by Django 2.2.24 on 2021-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0052_auto_20210929_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientapplicationbundle",
            name="email_required",
            field=models.BooleanField(default=True),
        ),
    ]
