# Generated by Django 2.2.25 on 2022-02-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_clientapplicationbundle_email_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
