# Generated by Django 4.0.3 on 2022-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0054_customuser_bundle_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bundle_id",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="creation bundle id"),
        ),
    ]
