# Generated by Django 4.0.5 on 2022-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0055_alter_customuser_bundle_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_accessed",
            field=models.DateTimeField(null=True, verbose_name="last accessed"),
        ),
    ]
