# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0002_auto_20160217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='token',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
