# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0004_paymentcardaccountimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccountImageCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCard')),
                ('payment_card_accounts', models.ManyToManyField(related_name='payment_card_accounts_set', to='payment_card.PaymentCardAccount')),
                ('payment_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.PaymentCardAccountImage')),
            ],
        ),
    ]
