# Generated by Django 1.9.2 on 2016-06-10 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_card", "0007_auto_20160610_1458"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentAccountImageCriteria",
            new_name="PaymentCardAccountImageCriteria",
        ),
    ]
