# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0008_auto_20160610_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcardaccountimagecriteria',
            old_name='payment_image',
            new_name='payment_card_image',
        ),
    ]
