# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0009_auto_20160610_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='fingerprint',
            field=models.CharField(max_length=100, null=True),
        )
    ]
