# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0010_paymentcardaccount_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='fingerprint',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
