# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0011_auto_20160620_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='fingerprint',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
