# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0013_auto_20160623_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='fingerprint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcardaccount',
            unique_together=set([]),
        ),
    ]
