# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 13:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0014_auto_20160629_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentcardaccount',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
