# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 16:28
from __future__ import unicode_literals

from django.db import migrations


def copy_tokens(apps, schema_editor):
    accounts = apps.get_model('payment_card', 'PaymentCardAccount').all_objects.all()
    for account in accounts:
        account.psp_token = account.token
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0020_auto_20160916_1628'),
    ]

    operations = [
        migrations.RunPython(copy_tokens)
    ]
