# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0022_auto_20160923_1025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentcardimage',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='size_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='strap_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardimage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
