# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0023_auto_20161017_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
