# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 11:36
from __future__ import unicode_literals

from django.db import migrations


def update_pan_end(apps, schema_editor):
    accounts = apps.get_model('payment_card', 'PaymentCardAccount').all_objects.all()
    for account in accounts:
        account.pan_end = account.pan_end[-4:]
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0025_auto_20161123_1628'),
    ]

    operations = [
        migrations.RunPython(update_pan_end)
    ]
