# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0032_auto_20170601_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccountimage',
            name='reward_tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentcardimage',
            name='reward_tier',
            field=models.IntegerField(default=0),
        ),
    ]
