# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0033_auto_20171123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='reward_tier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='paymentcardimage',
            name='reward_tier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
