# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0035_authtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='system',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Master Card'), ('amex', 'American Express')], max_length=40),
        ),
    ]
