# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0036_auto_20180629_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcardaccount',
            name='user',
        ),
    ]
