# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubiquity', '0001_initial'),
        ('payment_card', '0037_auto_20180824_1021'),
        ('scheme', '0045_auto_20180824_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='scheme_account_set',
            field=models.ManyToManyField(related_name='payment_card_account_set', through='ubiquity.PaymentCardSchemeEntry', to='scheme.SchemeAccount'),
        ),
        migrations.AddField(
            model_name='paymentcardaccount',
            name='user_set',
            field=models.ManyToManyField(related_name='payment_card_account_set', through='ubiquity.PaymentCardAccountEntry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcardaccountimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentcardimage',
            name='encoding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.Issuer'),
        ),
    ]
