# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-09 14:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0038_auto_20180703_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='consent',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
