# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 15:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0038_auto_20180703_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='consents',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.Issuer'),
        ),
    ]
