# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payment_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0060_auto_20190618_1526'),
        ('payment_card', '0039_paymentcarduserassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('transaction_ref', models.CharField(default=payment_card.models._generate_tx_ref, max_length=255)),
                ('transaction_token', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'AUTH_PENDING'), (1, 'AUTH_FAILED'), (2, 'AUTHORISED'), (3, 'SUCCESS'), (4, 'VOID_REQUIRED'), (5, 'VOID_SUCCESSFUL')], default=payment_card.models.PaymentStatus(0))),
                ('void_attempts', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('scheme_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.SchemeAccount')),
            ],
        ),
    ]
