# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0039_paymentcarduserassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='system',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express')], max_length=40),
        ),
    ]
