# Generated by Django 2.2.6 on 2019-10-15 13:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0041_paymentaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaudit',
            name='scheme_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheme.SchemeAccount'),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='consents',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_card.Issuer'),
        ),
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='payment_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_card.PaymentCard'),
        ),
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_card.PaymentCard'),
        ),
    ]
