# Generated by Django 2.2.10 on 2020-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0042_auto_20191015_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaudit',
            name='transaction_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
