# Generated by Django 3.0.4 on 2020-03-12 16:27

from django.db import migrations, models
import payment_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0042_auto_20191015_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaudit',
            name='status',
            field=models.IntegerField(choices=[(0, 'PURCHASE_PENDING'), (1, 'PURCHASE_FAILED'), (2, 'AUTHORISED'), (3, 'SUCCESSFUL'), (4, 'VOID_REQUIRED'), (5, 'VOID_SUCCESSFUL')], default=payment_card.models.PaymentStatus['PURCHASE_PENDING']),
        ),
        migrations.AlterField(
            model_name='paymentaudit',
            name='transaction_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
