# Generated by Django 2.2.10 on 2020-03-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0043_auto_20200313_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccountimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers'), (7, 'promotions'), (8, 'tier'), (9, 'alternative hero')]),
        ),
        migrations.AlterField(
            model_name='paymentcardimage',
            name='image_type_code',
            field=models.IntegerField(choices=[(0, 'hero'), (1, 'banner'), (2, 'offers'), (3, 'icon'), (4, 'asset'), (5, 'reference'), (6, 'personal offers'), (7, 'promotions'), (8, 'tier'), (9, 'alternative hero')]),
        ),
    ]
