# Generated by Django 2.2.11 on 2020-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0044_auto_20200316_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
