# Generated by Django 2.2.11 on 2020-03-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0045_paymentcardaccount_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentaudit',
            old_name='payment_card_id',
            new_name='payment_card_hash',
        ),
    ]
