# Generated by Django 2.2.11 on 2020-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0048_auto_20200428_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcardaccount',
            name='token',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
