# Generated by Django 2.2.11 on 2020-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0049_auto_20200501_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='activation_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
