# Generated by Django 2.2.11 on 2020-05-28 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import payment_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0049_auto_20200501_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicRetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_group', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'REQUIRED'), (1, 'PENDING'), (2, 'SUCCESSFUL'), (3, 'FAILED')], default=payment_card.models.PeriodicRetryStatus(0))),
                ('module', models.CharField(max_length=64)),
                ('function', models.CharField(max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('retry_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_retry_attempts', models.IntegerField(blank=True, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('next_retry_after', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
