# Generated by Django 2.2.11 on 2020-07-14 08:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def populate_pll_links(apps, schema_editor):
    PaymentCardAccount = apps.get_model('payment_card', 'PaymentCardAccount')
    PaymentCardSchemeEntry = apps.get_model('ubiquity', 'PaymentCardSchemeEntry')

    accounts = {}
    for link in PaymentCardSchemeEntry.objects.filter(active_link=True).all():
        formatted_link = {'id': link.scheme_account_id, 'active_link': True}

        if link.payment_card_account_id in accounts:
            account = accounts[link.payment_card_account_id]
            account.pll_links.append(formatted_link)

        else:
            account = link.payment_card_account
            account.pll_links = [formatted_link, ]
            accounts[account.id] = account

    PaymentCardAccount.all_objects.bulk_update(list(accounts.values()), ["pll_links"], batch_size=1000)


def revert_populate_pll_links(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('payment_card', '0050_payment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='pll_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.RunPython(populate_pll_links, revert_populate_pll_links)
    ]
