# Generated by Django 2.2.14 on 2021-01-05 18:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0053_auto_20201224_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcardaccount',
            name='agent_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
