# Generated by Django 4.2.4 on 2023-10-30 11:25

from django.db import migrations, models


def create_default_merchant_group(apps, schema_editor) -> None:
    VopMerchantGroup = apps.get_model("payment_card", "VopMerchantGroup")
    VopMerchantGroup.objects.create(offer_id=102411, group_name="BINK_DEFAULT_MRCH_GRP", default=True)


def revert_create_default_merchant_group(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("payment_card", "0058_delete_payment_card_different_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="VopMerchantGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("offer_id", models.IntegerField()),
                ("group_name", models.CharField()),
                ("default", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="vopmerchantgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default",),
                name="unique_default",
                violation_error_message="There can only be one default VopMerchantGroup",
            ),
        ),
        migrations.RunPython(create_default_merchant_group, revert_create_default_merchant_group),
    ]
