# Generated by Django 4.0.10 on 2023-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periodic_corrections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicretain",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="started"),
        ),
    ]
