from django.urls import re_path
from user.views import (
    Users,
    Register,
    NewRegister,
    Login,
    NewLogin,
    Authenticate,
    FaceBookLogin,
    TwitterLogin,
    ResetPassword,
    ApplyPromoCode,
    ForgotPassword,
    ValidateResetToken,
    ResetPasswordFromToken,
    Settings,
    UserSettings,
    IdentifyApplicationKit,
    VerifyToken,
    OrganisationTermsAndConditions,
    Logout,
)

urlpatterns = [
    re_path(r"authenticate/?$", Authenticate.as_view(), name="authenticate_user"),
    re_path(r"auth/facebook/?$", FaceBookLogin.as_view(), name="authenticate_facebook_user"),
    re_path(r"auth/twitter/?$", TwitterLogin.as_view(), name="authenticate_twitter_user"),
    re_path(r"^auth/verify_token/?$", VerifyToken.as_view(), name="verify_token"),
    re_path(r"^v2_register/?$", NewRegister.as_view(), name="new_register_user"),
    re_path(r"^register/?$", NewRegister.as_view(), name="register_user"),
    re_path(r"^v2_login/?$", NewLogin.as_view(), name="new_login"),
    re_path(r"^login/?$", NewLogin.as_view(), name="login"),
    re_path(r"me/?$", Users.as_view(), name="user_detail"),
    re_path(r"me/password/?$", ResetPassword.as_view(), name="reset_password"),
    re_path(r"me/settings/?$", UserSettings.as_view(), name="user_settings"),
    re_path(r"me/logout/?$", Logout.as_view(), name="logout"),
    re_path(r"forgotten_password/?$", ForgotPassword.as_view(), name="forgot_password"),
    re_path(r"reset_password/?$", ResetPasswordFromToken.as_view(), name="reset_password_from_token"),
    re_path(r"promo_code/?$", ApplyPromoCode.as_view(), name="promo_code"),
    re_path(r"validate_reset_token/?$", ValidateResetToken.as_view(), name="validate_reset"),
    re_path(r"settings/?$", Settings.as_view(), name="settings"),
    re_path(r"^app_kit/?$", IdentifyApplicationKit.as_view(), name="app_kit"),
    re_path(r"^renew_token/?$", views.Renew().as_view(), name="renew"),
    re_path(
        r"^organisation/terms_and_conditions/?$", OrganisationTermsAndConditions.as_view(), name="terms_and_conditions"
    ),
]
