name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      HERMES_DATABASE_URL: "postgresql+psycopg2://postgres@127.0.0.1:5432/hermes"
      RABBIT_DSN: "amqp://guest:guest@127.0.0.1:5672/"
      REDIS_URL: "redis://127.0.0.1:6379/1"
      JSON_LOGGING: False
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry install
      - run: ruff format . --check
      - run: xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: ruff check .
      - run: coverage run --source='.' manage.py test -v 2
      - run: coverage report
      - run: coverage xml
